### ISSUE TITLE
access_token deprecated

### ISSUE THREAD

**Issue by baburdick** [aleffert/PullRequestMenu#3]
Looks like GitHub wants this interaction to play out differently now. Do you have a fix in the works? Or are there difficulties?
```
Hi @baburdick,

On February 6th, 2020 at 21:42 (UTC) your personal access token (PullRequestMenu) using PullRequestMenu/7 CFNetwork/1121.1.2 Darwin/19.2.0 (x86_64) was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/issues

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

**Comment by baburdick** [comment]
Thank you, BTW for PullRequestMenu. It's become an integral part of my workflow.

**Comment by aleffert** [comment]
I hadn't noticed (I'm managing now) but should be an easy fix. Thanks for the heads up.

**Comment by aleffert** [comment]
Just submitted a fix. It should appear on the app store in a few days. Note that the next actionable date on this is September so we're well in front of this.

Thanks again for the flag and glad you're enjoying it!

**Comment by baburdick** [comment]
Any update from Apple on when the update will appear?

**Comment by aleffert** [comment]
oh hey sorry, this got held up in app store review (they want a proper support page and even though I made one, they're being irritatingly vague about what needs to be in it, it's basically whack-a-mole) and then I lost track of it

**Comment by aleffert** [comment]
thanks for the reminder, I'll take a look (noting that this isn't actually an issue until september)

**Comment by aleffert** [comment]
just fyi @baburdick this should be released now

**Comment by baburdick** [comment]
Confirmed! Running v1.3. Thank you!
